const products = [
  {
    id: 1,
    name: 'Aurora Noise-Canceling Headphones',
    category: 'Electronics',
    price: 149.99,
    description: 'Wireless over-ear headphones with active noise cancellation and all-day battery life.',
    rating: 4.7,
  },
  {
    id: 2,
    name: 'Nimbus Smartwatch',
    category: 'Electronics',
    price: 199,
    description: 'A lightweight smartwatch with fitness tracking, sleep insights, and notification support.',
    rating: 4.5,
  },
  {
    id: 3,
    name: 'Arcade Mechanical Keyboard',
    category: 'Electronics',
    price: 119,
    description: 'Compact mechanical keyboard with hot-swappable switches and RGB lighting.',
    rating: 4.8,
  },
  {
    id: 4,
    name: 'PixelFold Smartphone',
    category: 'Electronics',
    price: 499,
    description: 'Slim smartphone with a bright OLED display, fast charging, and a capable camera system.',
    rating: 4.6,
  },
  {
    id: 5,
    name: 'Cotton Cloud T-Shirt',
    category: 'Clothing',
    price: 24,
    description: 'Soft heavyweight cotton tee with a relaxed fit for everyday wear.',
    rating: 4.3,
  },
  {
    id: 6,
    name: 'TrailFlex Running Jacket',
    category: 'Clothing',
    price: 89.5,
    description: 'Breathable water-resistant jacket designed for layering on cool morning runs.',
    rating: 4.6,
  },
  {
    id: 7,
    name: 'Everyday Denim Jacket',
    category: 'Clothing',
    price: 74,
    description: 'Classic mid-weight jacket with a modern fit and durable stitching.',
    rating: 4.4,
  },
  {
    id: 8,
    name: 'Oakline Coffee Table',
    category: 'Home Goods',
    price: 179.99,
    description: 'Minimal oak-finish coffee table with rounded edges and a durable matte top.',
    rating: 4.4,
  },
  {
    id: 9,
    name: 'Luna Ceramic Lamp',
    category: 'Home Goods',
    price: 64,
    description: 'Warm ambient table lamp with a ceramic base and linen shade.',
    rating: 4.2,
  },
  {
    id: 10,
    name: 'Harbor Throw Pillow Set',
    category: 'Home Goods',
    price: 42,
    description: 'Textured decorative pillows that add warmth to a sofa or bed.',
    rating: 4.5,
  },
  {
    id: 11,
    name: 'ChefPro Blender',
    category: 'Kitchen',
    price: 129.99,
    description: 'High-speed blender built for smoothies, sauces, and frozen ingredients.',
    rating: 4.8,
  },
  {
    id: 12,
    name: 'Bamboo Cutting Board Set',
    category: 'Kitchen',
    price: 38,
    description: 'Three-piece cutting board set made from durable bamboo with easy-grip handles.',
    rating: 4.5,
  },
  {
    id: 13,
    name: 'Espresso Milk Frother',
    category: 'Kitchen',
    price: 29.99,
    description: 'Handheld frother for lattes, cappuccinos, and quick kitchen drinks.',
    rating: 4.4,
  },
  {
    id: 14,
    name: 'GlowSkin Vitamin C Serum',
    category: 'Beauty',
    price: 29.99,
    description: 'Brightening facial serum with lightweight hydration and daily antioxidant support.',
    rating: 4.1,
  },
  {
    id: 15,
    name: 'Pulse Yoga Mat',
    category: 'Fitness',
    price: 45,
    description: 'Non-slip cushioned yoga mat with a durable surface for home workouts.',
    rating: 4.7,
  },
  {
    id: 16,
    name: 'Stride Adjustable Dumbbells',
    category: 'Fitness',
    price: 249,
    description: 'Space-saving dumbbells with quick-adjust weight settings for home training.',
    rating: 4.8,
  },
  {
    id: 17,
    name: 'Strategy Playbook',
    category: 'Books',
    price: 18.5,
    description: 'A practical guide to decision-making, planning, and building better habits.',
    rating: 4.6,
  },
  {
    id: 18,
    name: 'Weekend Travel Backpack',
    category: 'Accessories',
    price: 92,
    description: 'Carry-on friendly backpack with a laptop sleeve and weather-resistant shell.',
    rating: 4.7,
  },
]

export default products
