import { useEffect, useState } from 'react'
import { getProducts, getRecommendations } from './recommendationService'
import './App.css'

const examplePrompts = [
  'I want a phone under $500',
  'I need a gift for someone who likes home decor',
  'Show me fitness gear for daily workouts',
]

function App() {
  const [products, setProducts] = useState([])
  const [preference, setPreference] = useState('I want a phone under $500')
  const [recommendation, setRecommendation] = useState(null)
  const [status, setStatus] = useState('idle')
  const [productsStatus, setProductsStatus] = useState('loading')
  const [productsError, setProductsError] = useState('')
  const [error, setError] = useState('')

  useEffect(() => {
    let isMounted = true

    const loadProducts = async () => {
      try {
        const items = await getProducts()

        if (isMounted) {
          setProducts(items)
          setProductsStatus('ready')
        }
      } catch {
        if (isMounted) {
          setProductsError('Unable to load products from the backend.')
          setProductsStatus('error')
        }
      }
    }

    loadProducts()

    return () => {
      isMounted = false
    }
  }, [])

  const handleSubmit = async (event) => {
    event.preventDefault()

    const trimmedPreference = preference.trim()

    if (!trimmedPreference) {
      setError('Enter a preference so the AI has something to work with.')
      return
    }

    setError('')
    setStatus('loading')

    try {
      const result = await getRecommendations(trimmedPreference)
      setRecommendation(result)
      setStatus('success')

      // Fetch the updated catalog from the backend to display the newly generated products
      const items = await getProducts()
      setProducts(items)
    } catch (submissionError) {
      setError(
        submissionError instanceof Error
          ? submissionError.message
          : 'Something went wrong while generating recommendations.',
      )
      setStatus('error')
    }
  }

  return (
    <main className="app-shell">
      <section className="hero-panel">
        <div className="eyebrow">AI Product Recommendation System</div>
        <h1>Describe what you want and let the AI recommend products.</h1>
        <p className="hero-copy">
          Type a shopping preference, send it to the backend API, and get back
          product recommendations generated dynamically by Gemini AI.
        </p>

        <form className="search-panel" onSubmit={handleSubmit}>
          <label htmlFor="preference">Your preference</label>
          <textarea
            id="preference"
            value={preference}
            onChange={(event) => setPreference(event.target.value)}
            placeholder="For example: I want a phone under $500"
            rows="4"
          />

          <div className="example-row" aria-label="Example prompts">
            {examplePrompts.map((examplePrompt) => (
              <button
                key={examplePrompt}
                type="button"
                className="ghost-chip"
                onClick={() => setPreference(examplePrompt)}
              >
                {examplePrompt}
              </button>
            ))}
          </div>

          <div className="action-row">
            <button type="submit" className="primary-button" disabled={status === 'loading'}>
              {status === 'loading' ? 'Finding matches...' : 'Ask AI for recommendations'}
            </button>
            <span className="hint-text">Recommendations are generated by the backend.</span>
          </div>
        </form>

        <div className="status-strip">
          <span className={`status-pill status-${status}`}>
            {status === 'loading'
              ? 'Querying AI'
              : status === 'success'
                ? recommendation?.source === 'ai'
                  ? 'AI-ranked results'
                  : 'Local fallback results'
                : status === 'error'
                  ? 'Request failed'
                  : 'Ready to search'}
          </span>
          <span>
            {productsStatus === 'ready'
              ? `${products.length} products in the catalog`
              : productsStatus === 'loading'
                ? 'Loading products...'
                : 'Products unavailable'}
          </span>
        </div>

        {productsError ? <p className="error-banner">{productsError}</p> : null}
        {error ? <p className="error-banner">{error}</p> : null}
      </section>

      <section className="content-grid">
        <article className="results-card">
          <div className="section-header">
            <div>
              <p className="section-kicker">Recommendation output</p>
              <h2>Best matches</h2>
            </div>
            {recommendation ? (
              <span className="source-tag">{recommendation.source}</span>
            ) : null}
          </div>

          {recommendation ? (
            <div className="recommendation-stack">
              <p className="summary-text">{recommendation.explanation}</p>

              <div className="recommendation-list">
                {recommendation.products.map((product, index) => (
                  <article key={product.id} className="recommendation-item">
                    <div className="recommendation-rank">0{index + 1}</div>
                    <div>
                      <div className="recommendation-meta">
                        <span>{product.category}</span>
                        <span>Rating {product.rating.toFixed(1)}</span>
                      </div>
                      <h3>{product.name}</h3>
                      <p>{product.description}</p>
                    </div>
                    <strong className="recommendation-price">${product.price.toFixed(2)}</strong>
                  </article>
                ))}
              </div>
            </div>
          ) : (
            <div className="empty-state">
              <h3>No recommendation yet</h3>
              <p>
                Enter a shopping preference and press the button to generate
                AI recommendations using the Gemini API.
              </p>
            </div>
          )}
        </article>

        <article className="catalog-card">
          <div className="section-header">
            <div>
              <p className="section-kicker">Curated catalog</p>
              <h2>Available products</h2>
            </div>
            <span className="catalog-note">Growing dynamically as AI generates recommendations</span>
          </div>

          <div className="product-grid">
            {products.map((product) => {
              const isRecommended = recommendation?.products.some(
                (recommendedProduct) => recommendedProduct.id === product.id,
              )

              return (
                <article
                  key={product.id}
                  className={`product-card${isRecommended ? ' product-card-highlight' : ''}`}
                >
                  <div className="product-card-top">
                    <span className="category-badge">{product.category}</span>
                    <span className="rating-badge">{product.rating.toFixed(1)} / 5</span>
                  </div>
                  <h3>{product.name}</h3>
                  <p>{product.description}</p>
                  <div className="product-card-bottom">
                    <strong>${product.price.toFixed(2)}</strong>
                    {isRecommended ? <span>Recommended</span> : <span>&nbsp;</span>}
                  </div>
                </article>
              )
            })}
          </div>
        </article>
      </section>
    </main>
  )
}

export default App
